### ISSUE TITLE
Vesuvius links not working

### ISSUE THREAD

**Issue by ykessler** [tagliala/vesuvius#13]
Hi- I'm trying to create a GEOS buildpack for Heroku but the Vesuvius app is link not working: https://vesuvius.herokuapp.com/

Nor are the links to the compiled libraries listed here: https://github.com/diowa/heroku-buildpack-vendorbinaries#vendorfile

- https://vesuvius.herokuapp.com/libraries/geos-3.10.0-heroku.tar.gz
- https://vesuvius.herokuapp.com/libraries/proj-8.1.1-heroku.tar.gz

**Comment by tagliala** [comment]
Hi @ykessler, I've just received a new email from Heroku which clarifies what I need to do to qualify again for open source credits

I will try to apply again

**Comment by tagliala** [comment]
Credits required, waiting for an answer

**Comment by tagliala** [comment]
My credits were approved, but I did not meet a deadline for the 25th of May because I forgot to add Code of Conduct to the repositories I've requested credits for

Sorry, but I have limited time resources and for the moment I will not continue to invest time here
